package AdivinhaNumeroApp;


/**
* AdivinhaNumeroApp/AdivinhaNumero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdivinhaNumero.idl
* Saturday, December 8, 2018 2:18:10 PM BRST
*/

public interface AdivinhaNumero extends AdivinhaNumeroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdivinhaNumero
