package AdivinhaNumeroApp;


/**
* AdivinhaNumeroApp/AdivinhaNumero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdivinhaNumero.idl
* jueves 17 de marzo de 2022 04H01' CET
*/

public interface AdivinhaNumero extends AdivinhaNumeroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdivinhaNumero
