package AdivinhaNumeroApp;


/**
* AdivinhaNumeroApp/AdivinhaNumeroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdivinhaNumero.idl
* jueves 17 de marzo de 2022 04H01' CET
*/

public interface AdivinhaNumeroOperations 
{
  int identifica ();
  int retornaresultado ();
  int inicio ();
  int verifica (int id, int tentativa);
} // interface AdivinhaNumeroOperations
