package AdivinhaNumeroApp;


/**
* AdivinhaNumeroApp/AdivinhaNumeroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdivinhaNumero.idl
* Saturday, December 8, 2018 2:18:10 PM BRST
*/

public interface AdivinhaNumeroOperations 
{
  int identifica ();
  int retornaresultado ();
  int inicio ();
  int verifica (int id, int tentativa);
} // interface AdivinhaNumeroOperations
