package AdivinhaNumeroApp;


/**
* AdivinhaNumeroApp/AdivinhaNumeroHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdivinhaNumero.idl
* jueves 17 de marzo de 2022 04H01' CET
*/

abstract public class AdivinhaNumeroHelper
{
  private static String  _id = "IDL:AdivinhaNumeroApp/AdivinhaNumero:1.0";

  public static void insert (org.omg.CORBA.Any a, AdivinhaNumeroApp.AdivinhaNumero that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AdivinhaNumeroApp.AdivinhaNumero extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AdivinhaNumeroApp.AdivinhaNumeroHelper.id (), "AdivinhaNumero");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AdivinhaNumeroApp.AdivinhaNumero read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AdivinhaNumeroStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AdivinhaNumeroApp.AdivinhaNumero value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AdivinhaNumeroApp.AdivinhaNumero narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AdivinhaNumeroApp.AdivinhaNumero)
      return (AdivinhaNumeroApp.AdivinhaNumero)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AdivinhaNumeroApp._AdivinhaNumeroStub stub = new AdivinhaNumeroApp._AdivinhaNumeroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AdivinhaNumeroApp.AdivinhaNumero unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AdivinhaNumeroApp.AdivinhaNumero)
      return (AdivinhaNumeroApp.AdivinhaNumero)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AdivinhaNumeroApp._AdivinhaNumeroStub stub = new AdivinhaNumeroApp._AdivinhaNumeroStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
