package AdivinhaNumeroApp;

/**
* AdivinhaNumeroApp/AdivinhaNumeroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AdivinhaNumero.idl
* jueves 17 de marzo de 2022 04H01' CET
*/

public final class AdivinhaNumeroHolder implements org.omg.CORBA.portable.Streamable
{
  public AdivinhaNumeroApp.AdivinhaNumero value = null;

  public AdivinhaNumeroHolder ()
  {
  }

  public AdivinhaNumeroHolder (AdivinhaNumeroApp.AdivinhaNumero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdivinhaNumeroApp.AdivinhaNumeroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdivinhaNumeroApp.AdivinhaNumeroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdivinhaNumeroApp.AdivinhaNumeroHelper.type ();
  }

}
